# Generated by VibeNest — multi-stage Vite SPA build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
# `npm ci` is faster + reproducible when package-lock.json matches package.json,
# but real-world repos often have lockfile drift (added a dep without committing
# the lock update, etc.). Falling back to `npm install` keeps the build resilient
# without sacrificing the happy-path performance.
RUN npm ci || npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]